# Generated by Django 2.1 on 2018-08-20 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_review_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='body',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='type',
            field=models.CharField(choices=[('movie', 'Movie'), ('television', 'Television'), ('song', 'Song'), ('album', 'Album'), ('artist', 'Artist'), ('book', 'Book')], max_length=16),
        ),
    ]
