# Generated by Django 2.1 on 2018-08-22 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_auto_20180821_2156'),
        ('reviews', '0003_auto_20180819_2336'),
    ]

    operations = [
    ]
