# Generated by Django 2.1 on 2018-08-03 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0005_auto_20180801_1633'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='movie_id',
            new_name='api_id',
        ),
        migrations.AddField(
            model_name='review',
            name='type',
            field=models.CharField(choices=[('song', 'Song'), ('movie', 'Movie')], default='movie', max_length=16),
            preserve_default=False,
        ),
    ]
